### ISSUE TITLE
External modules fail to load  when  CONFIG_DEBUG_INFO_BTF and CPU optimisation is used

### ISSUE THREAD

**Issue by Thaodan** [graysky2/kernel_gcc_patch#70] opened 2021-04-13 15:35 UTC
If noticed when using `CONFIG_DEBUG_INFO_BTF` and `CONIG_M$CPU` is used because external modules are broken because they fail to load:

```
[  +0,003082] BPF:[94156] TYPEDEF  
[  +0,001717] BPF:type_id=94174
[  +0,001684] BPF: 
[  +0,001662] BPF:Invalid name
[  +0,001579] BPF:
[  +0,003050] failed to validate module [vboxdrv] BTF: -22
```

full log:

[dmesg.log](https://github.com/graysky2/kernel_gcc_patch/files/6304845/dmesg.log)

Kernel version used: 5.11.11-pf6-1
CPU optimization: Zen2

There is no difference between modules build with dkms (e.g. the one mentioned above) or modules like the nvidia driver.

Looking into DKMS they use -mtune=generic while building, I don't know if that is the issue since before using `CONFIG_DEBUG_INFO_BTF` that was just fine.

**Comment by graysky2** [comment] 2021-04-13 18:08
Can you try it on the vanilla kernel.

**Comment by Thaodan** [comment] 2021-04-25 12:18
I tried arch kernel no issues there. Seems to be a pf issue. I build in a clean chroot there should be no issue regarding my build host. I need to try -ck kernels.

**Comment by graysky2** [comment] 2021-04-25 12:26
OK, if the Arch kernel + this patch is good, I agree with you that the issue is not the patch but something in your other kernel.  Closing.  Reopen if you find evidence to the contrary.

**Closed by graysky2** 2021-04-25 12:26 UTC
